data:
  dataset:
    name: caltech-imagenet # choices are ['office', 'officehome', 'caltech-imagenet', 'visda2017']
    root_path: /data1/yinmingyue/Datasets # /path/to/dataset/root
    source: 2 # source domain index, if imagenet-caltech, source: 2   if caltech-imagenet, source: 0
    target: 1 # target domain index, if imagenet-caltech, target: 1   if caltech-imagenet, target: 3
    n_share: 84 # number of classes to be shared
    n_source_private: 173 # number of classes in source private domain
    n_total: 1173 # number of classes in total

  dataloader:
    class_balance: true # if class_balance when loading datasets
    data_workers: 0 # how many workers to use for train dataloaders
    batch_size: 30 # batch_size for source domain and target domain respectively

model:
  base_model: vgg16 # choices=['resnet50', 'vgg16']
  pretrained_model: /home/yinmingyue/.torch/models/vgg16-397923af.pth # /path/to/pretrained/model

train:
  min_step: 200000 # minimum steps to run. run epochs until it exceeds the minStep
  lr: 0.01 # learning rate for new layers. learning rate for finetune is 1/10 of lr
  weight_decay: 0.0005 # weight_decay for SGD optimizer
  momentum: 0.9  # momentum for SGD optimizer
  cut: .0  # cut threshold for normalizing weights

test:
  test_interval: 500 # interval of two continuous test phase, if imagenet-caltech, test_interval: 20000
  test_only: False # test a given model and exit

misc:
  gpus: 1  # how many GPUs to be used, 0 indicates CPU only, needed GPU memory < 19 GB
  gpu_id: "0"  # which GPU you want to use
  gpu_id_list: [0] # [0,...,gpus-1]

log:
  root_dir: log # the log directory (log directory will be {root_dir}/{method}/time/)
  log_interval: 10 # steps to log scalars